# -*- coding: utf-8 -*-
#
# THIS FILE IS AUTOGENERATED WITH ANSIBLE!
# Do not edit it directly
#
# Глобальные ключи
GLOBALS = {
    'WITH_LOOPPROTECT_PATCH': False,
    'WITH_ASYNC_FRAMEWORK': False,
    'DEFINE_RTPENGINE_IP': '"sip_ip"',
    'MEDIASERVER': 'sip:127.0.0.1:5060',
    'WHITELIST_ID': 1,
}

# Аплинки
DSIDS = {
    'MEDIASERVERS': 1,
    'CALLERS': 2,
    'GW': 28,
}

# Флаги камаилио
FLAGS = {
    'FLT_NATS': 7,
    'FLT_FROM_SUBSCRIBER': 10,
    'FLT_TO_SUBSCRIBER': 11,
    'FLT_MAX_BRANCHES': 30,
    'FLB_NATB': 6,
    'FLB_NATSIPPING': 7,
    'FLT_FROM_ASTERISK': 29,
    'FLT_FROM_GW': 28,
    'FLT_SKIP_AUTH': 6,
}

